class PyLangISO639_2:
    _code_to_name = {
        "zho": "Chinese",
        "spa": "Spanish",
        "eng": "English",
        "hin": "Hindi",
        "arb": "Arabic",
        "ben": "Bengali",
        "por": "Portuguese",
        "rus": "Russian",
        "jpn": "Japanese",
        "pan": "Punjabi",
        "deu": "German",
        "jav": "Javanese",
        "kor": "Korean",
        "fra": "French",
        "tur": "Turkish",
        "vie": "Vietnamese",
        "tam": "Tamil",
        "mar": "Marathi",
        "ita": "Italian",
        "tha": "Thai",
        "guj": "Gujarati",
        "kan": "Kannada",
        "urd": "Urdu",
        "pol": "Polish",
        "ukr": "Ukrainian",
        "mal": "Malayalam",
        "ori": "Odia",
        "ceb": "Cebuano",
        "heb": "Hebrew",
        "ron": "Romanian",
        "nld": "Dutch",
        "ell": "Greek",
        "swa": "Swahili",
        "amh": "Amharic",
        "sin": "Sinhala",
        "khm": "Khmer",
        "lao": "Lao",
        "bul": "Bulgarian",
        "swe": "Swedish",
        "srp": "Serbian",
        "aze": "Azerbaijani",
        "ces": "Czech",
        "hun": "Hungarian",
        "uzb": "Uzbek",
        "tgk": "Tajik",
        "kir": "Kyrgyz",
        "tuk": "Turkmen",
        "tat": "Tatar",
        "bak": "Bashkir",
        "aar": "Afar",
        "abk": "Abkhazian",
        "ace": "Achinese",
        "ach": "Acoli",
        "ada": "Adangme",
        "ady": "Adyghe",
        "afa": "Afro-Asiatic languages",
        "afh": "Afrihili",
        "afr": "Afrikaans",
        "ain": "Ainu",
        "aka": "Akan",
        "akk": "Akkadian",
        "ale": "Aleut",
        "alg": "Algonquian languages",
        "alt": "Southern Altai",
        "ang": "English, Old (ca.450–1100)",
        "anp": "Angika",
        "apa": "Apache languages",
        "ara": "Arabic",
        "arc": "Official Aramaic (700–300 BCE)",
        "arg": "Aragonese",
        "arn": "Mapudungun",
        "arp": "Arapaho",
        "art": "Artificial languages",
        "arw": "Arawak",
        "asm": "Assamese",
        "ast": "Asturian",
        "ath": "Athapascan languages",
        "aus": "Australian languages",
        "ava": "Avaric",
        "ave": "Avestan",
        "awa": "Awadhi",
        "aym": "Aymara",
        "bad": "Banda languages",
        "bai": "Bamileke languages",
        "bal": "Baluchi",
        "bam": "Bambara",
        "ban": "Balinese",
        "bas": "Basa",
        "bat": "Baltic languages",
        "bej": "Beja",
        "bel": "Belarusian",
        "bem": "Bemba",
        "bho": "Bhojpuri",
        "bih": "Bihari languages",
        "bik": "Bikol",
        "bin": "Bini",
        "bis": "Bislama",
        "bla": "Siksika",
        "bnt": "Bantu languages",
        "bod": "Tibetan",
        "bos": "Bosnian",
        "bra": "Braj",
        "bre": "Breton",
        "btk": "Batak languages",
        "bua": "Buriat",
        "bug": "Buginese",
        "byn": "Blin",
        "cad": "Caddo",
        "cai": "Central American Indian languages",
        "car": "Galibi Carib",
        "cat": "Catalan",
        "cau": "Caucasian languages",
        "cha": "Chamorro",
        "chb": "Chibcha",
        "che": "Chechen",
        "chg": "Chagatai",
        "chk": "Chuukese",
        "chm": "Mari",
        "chn": "Chinook Jargon",
        "cho": "Choctaw",
        "chp": "Chipewyan",
        "chr": "Cherokee",
        "chu": "Church Slavic",
        "chv": "Chuvash",
        "chy": "Cheyenne",
        "cmc": "Chamic languages",
        "cnr": "Montenegrin",
        "cop": "Coptic",
        "cor": "Cornish",
        "cos": "Corsican",
        "cpe": "Creoles and pidgins, English based",
        "cpf": "Creoles and pidgins, French-based",
        "cpp": "Creoles and pidgins, Portuguese-based",
        "cre": "Cree",
        "crh": "Crimean Tatar",
        "crp": "Creoles and pidgins",
        "csb": "Kashubian",
        "cus": "Cushitic languages",
        "cym": "Welsh",
        "dak": "Dakota",
        "dan": "Danish",
        "dar": "Dargwa",
        "day": "Land Dayak languages",
        "del": "Delaware",
        "den": "Slave (Athapascan)",
        "dgr": "Tlicho",
        "din": "Dinka",
        "div": "Divehi",
        "doi": "Dogri",
        "dra": "Dravidian languages",
        "dsb": "Lower Sorbian",
        "dua": "Duala",
        "dum": "Dutch, Middle (ca. 1050–1350)",
        "dyu": "Dyula",
        "dzo": "Dzongkha",
        "efi": "Efik",
        "egy": "Egyptian (Ancient)",
        "eka": "Ekajuk",
        "elx": "Elamite",
        "enm": "English, Middle (1100–1500)",
        "epo": "Esperanto",
        "est": "Estonian",
        "eus": "Basque",
        "ewe": "Ewe",
        "ewo": "Ewondo",
        "fan": "Fang",
        "fao": "Faroese",
        "fas": "Persian",
        "fat": "Fanti",
        "fij": "Fijian",
        "fil": "Filipino",
        "fin": "Finnish",
        "fiu": "Finno-Ugrian languages",
        "fon": "Fon",
        "frm": "French, Middle (ca. 1400–1600)",
        "fro": "French, Old (842–ca. 1400)",
        "frr": "Northern Frisian",
        "frs": "Eastern Frisian",
        "fry": "Western Frisian",
        "ful": "Fulah",
        "fur": "Friulian",
        "gaa": "Ga",
        "gay": "Gayo",
        "gba": "Gbaya",
        "gem": "Germanic languages",
        "gez": "Geez",
        "gil": "Gilbertese",
        "gla": "Gaelic",
        "gle": "Irish",
        "glg": "Galician",
        "glv": "Manx",
        "gmh": "German, Middle High (ca. 1050–1500)",
        "goh": "German, Old High (ca. 750–1050)",
        "gon": "Gondi",
        "gor": "Gorontalo",
        "got": "Gothic",
        "grb": "Grebo",
        "grc": "Greek, Ancient (to 1453)",
        "grn": "Guarani",
        "gsw": "Swiss German",
        "gwi": "Gwich'in",
        "hai": "Haida",
        "hat": "Haitian",
        "hau": "Hausa",
        "haw": "Hawaiian",
        "her": "Herero",
        "hil": "Hiligaynon",
        "him": "Himachali languages",
        "hit": "Hittite",
        "hmn": "Hmong",
        "hmo": "Hiri Motu",
        "hrv": "Croatian",
        "hsb": "Upper Sorbian",
        "hup": "Hupa",
        "hye": "Armenian",
        "iba": "Iban",
        "ibo": "Igbo",
        "ido": "Ido",
        "iii": "Sichuan Yi",
        "ijo": "Ijo languages",
        "iku": "Inuktitut",
        "ile": "Interlingue",
        "ilo": "Iloko",
        "ina": "Interlingua (International Auxiliary Language Association)",
        "inc": "Indic languages",
        "ind": "Indonesian",
        "ine": "Indo-European languages",
        "inh": "Ingush",
        "ipk": "Inupiaq",
        "ira": "Iranian languages",
        "iro": "Iroquoian languages",
        "isl": "Icelandic",
        "jav": "Javanese",
        "jbo": "Lojban",
        "jpr": "Judeo-Persian",
        "jrb": "Judeo-Arabic",
        "kaa": "Kara-Kalpak",
        "kab": "Kabyle",
        "kac": "Kachin",
        "kal": "Kalaallisut",
        "kam": "Kamba",
        "kar": "Karen languages",
        "kas": "Kashmiri",
        "kat": "Georgian",
        "kau": "Kanuri",
        "kaw": "Kawi",
        "kaz": "Kazakh",
        "kbd": "Kabardian",
        "kha": "Khasi",
        "khi": "Khoisan languages",
        "kho": "Khotanese",
        "kik": "Kikuyu",
        "kin": "Kinyarwanda",
        "kir": "Kirghiz",
        "kmb": "Kimbundu",
        "kok": "Konkani",
        "kom": "Komi",
        "kon": "Kongo",
        "kos": "Kosraean",
        "kpe": "Kpelle",
        "krc": "Karachay-Balkar",
        "krl": "Karelian",
        "kro": "Kru languages",
        "kru": "Kurukh",
        "kua": "Kuanyama",
        "kum": "Kumyk",
        "kur": "Kurdish",
        "kut": "Kutenai",
        "lad": "Ladino",
        "lah": "Lahnda",
        "lam": "Lamba",
        "lat": "Latin",
        "lav": "Latvian",
        "lez": "Lezghian",
        "lim": "Limburgan",
        "lin": "Lingala",
        "lit": "Lithuanian",
        "lol": "Mongo",
        "loz": "Lozi",
        "ltz": "Luxembourgish",
        "lua": "Luba-Lulua",
        "lub": "Luba-Katanga",
        "lug": "Ganda",
        "lui": "Luiseno",
        "lun": "Lunda",
        "luo": "Luo (Kenya and Tanzania)",
        "lus": "Lushai",
        "mad": "Madurese",
        "mag": "Magahi",
        "mah": "Marshallese",
        "mai": "Maithili",
        "mak": "Makasar",
        "man": "Mandingo",
        "map": "Austronesian languages",
        "mas": "Masai",
        "mdf": "Moksha",
        "mdr": "Mandar",
        "men": "Mende",
        "mga": "Irish, Middle (900–1200)",
        "mic": "Mi'kmaq",
        "min": "Minangkabau",
        "mis": "Uncoded languages",
        "mkd": "Macedonian",
        "mkh": "Mon-Khmer languages",
        "mlg": "Malagasy",
        "mlt": "Maltese",
        "mnc": "Manchu",
        "mni": "Manipuri",
        "mno": "Manobo languages",
        "moh": "Mohawk",
        "mon": "Mongolian",
        "mos": "Mossi",
        "mri": "Maori",
        "msa": "Malay",
        "mul": "Multiple languages",
        "mun": "Munda languages",
        "mus": "Creek",
        "mwl": "Mirandese",
        "mwr": "Marwari",
        "mya": "Burmese",
        "myn": "Mayan languages",
        "myv": "Erzya",
        "nah": "Nahuatl languages",
        "nai": "North American Indian languages",
        "nap": "Neapolitan",
        "nau": "Nauru",
        "nav": "Navajo",
        "nbl": "Ndebele, South",
        "nde": "Ndebele, North",
        "ndo": "Ndonga",
        "nds": "Low German",
        "nep": "Nepali",
        "new": "Nepal Bhasa",
        "nia": "Nias",
        "nic": "Niger-Kordofanian languages",
        "niu": "Niuean",
        "nno": "Norwegian Nynorsk",
        "nob": "Bokmål, Norwegian",
        "nog": "Nogai",
        "non": "Norse, Old",
        "nor": "Norwegian",
        "nqo": "N'Ko",
        "nso": "Pedi",
        "nub": "Nubian languages",
        "nwc": "Classical Newari",
        "nya": "Chichewa",
        "nym": "Nyamwezi",
        "nyn": "Nyankole",
        "nyo": "Nyoro",
        "nzi": "Nzima",
        "oci": "Occitan (post 1500)",
        "oji": "Ojibwa",
        "orm": "Oromo",
        "osa": "Osage",
        "oss": "Ossetian",
        "ota": "Turkish, Ottoman (1500–1928)",
        "oto": "Otomian languages",
        "paa": "Papuan languages",
        "pag": "Pangasinan",
        "pal": "Pahlavi",
        "pam": "Pampanga",
        "pap": "Papiamento",
        "pau": "Palauan",
        "peo": "Persian, Old (c. 600–400 B.C.)",
        "phi": "Philippine languages",
        "phn": "Phoenician",
        "pli": "Pali",
        "pon": "Pohnpeian",
        "pra": "Prakrit languages",
        "pro": "Provençal, Old (to 1500)",
        "pus": "Pushto",
        "qaa-qtz": "Reserved for local use",
        "que": "Quechua",
        "raj": "Rajasthani",
        "rap": "Rapanui",
        "rar": "Rarotongan",
        "roa": "Romance languages",
        "roh": "Romansh",
        "rom": "Romany",
        "run": "Rundi",
        "rup": "Aromanian",
        "rus": "Russian",
        "sad": "Sandawe",
        "sag": "Sango",
        "sah": "Yakut",
        "sai": "South American Indian languages",
        "sal": "Salishan languages",
        "sam": "Samaritan Aramaic",
        "san": "Sanskrit",
        "sas": "Sasak",
        "sat": "Santali",
        "scn": "Sicilian",
        "sco": "Scots",
        "sel": "Selkup",
        "sem": "Semitic languages",
        "sga": "Irish, Old (to 900)",
        "sgn": "Sign languages",
        "shn": "Shan",
        "sid": "Sidamo",
        "sio": "Siouan languages",
        "sit": "Sino-Tibetan languages",
        "sla": "Slavic languages",
        "slk": "Slovak",
        "slv": "Slovenian",
        "sma": "Southern Sami",
        "sme": "Northern Sami",
        "smi": "Sami languages",
        "smj": "Lule Sami",
        "smn": "Inari Sami",
        "smo": "Samoan",
        "sms": "Skolt Sami",
        "sna": "Shona",
        "snd": "Sindhi",
        "snk": "Soninke",
        "sog": "Sogdian",
        "som": "Somali",
        "son": "Songhai languages",
        "sot": "Sotho, Southern",
        "sqi": "Albanian",
        "srd": "Sardinian",
        "srn": "Sranan Tongo",
        "srr": "Serer",
        "ssa": "Nilo-Saharan languages",
        "ssw": "Swati",
        "suk": "Sukuma",
        "sun": "Sundanese",
        "sus": "Susu",
        "sux": "Sumerian",
        "syc": "Classical Syriac",
        "syr": "Syriac",
        "tah": "Tahitian",
        "tai": "Tai languages",
        "tel": "Telugu",
        "tem": "Timne",
        "ter": "Tereno",
        "tet": "Tetum",
        "tgl": "Tagalog",
        "tig": "Tigre",
        "tir": "Tigrinya",
        "tiv": "Tiv",
        "tkl": "Tokelau",
        "tlh": "Klingon",
        "tli": "Tlingit",
        "tmh": "Tamashek",
        "tog": "Tonga (Nyasa)",
        "ton": "Tonga (Tonga Islands)",
        "tpi": "Tok Pisin",
        "tsn": "Tswana",
        "tso": "Tsonga",
        "tum": "Tumbuka",
        "tup": "Tupi languages",
        "tut": "Altaic languages",
        "tvl": "Tuvalu",
        "twi": "Twi",
        "tyv": "Tuvinian",
        "udm": "Udmurt",
        "uga": "Ugaritic",
        "uig": "Uighur",
        "umb": "Umbundu",
        "und": "Undetermined",
        "urd": "Urdu",
        "vai": "Vai",
        "ven": "Venda",
        "vol": "Volapük",
        "vot": "Votic",
        "wak": "Wakashan languages",
        "wal": "Wolaitta",
        "war": "Waray",
        "was": "Washo",
        "wen": "Sorbian languages",
        "wln": "Walloon",
        "wol": "Wolof",
        "xal": "Kalmyk",
        "xho": "Xhosa",
        "yao": "Yao",
        "yap": "Yapese",
        "yid": "Yiddish",
        "yor": "Yoruba",
        "ypk": "Yupik languages",
        "zap": "Zapotec",
        "zbl": "Blissymbols",
        "zen": "Zenaga",
        "zgh": "Standard Moroccan Tamazight",
        "zha": "Zhuang",
        "znd": "Zande languages",
        "zul": "Zulu",
        "zun": "Zuni",
        "zxx": "No linguistic content",
        "zza": "Zaza",
    }
    _name_to_code = {v.lower(): k for k, v in _code_to_name.items()}

    _T_to_B_map = {
        "deu": "ger",
        "fra": "fre",
        "sqi": "alb",
        "ron": "rum",
        "ces": "cze",
        "mya": "bur",
        "zho": "chi",
        "ell": "gre",
        "nld": "dut",
        "bod": "tib",
        "cym": "wel",
        "fas": "per",
        "hye": "arm",
        "isl": "ice",
        "kat": "geo",
        "mkd": "mac",
        "mri": "mao",
        "msa": "may",
        "slk": "slo",
        "yid": "yid",
    }

    _B_to_T_map = {v: k for k, v in _T_to_B_map.items()}

    @classmethod
    def code_to_name(cls, code: str) -> str:
        code = code.lower()
        # Normalize bibliographic codes to terminologic if needed
        if code in cls._B_to_T_map:
            code = cls._B_to_T_map[code]
        return cls._code_to_name.get(code, "")

    @classmethod
    def name_to_code(cls, name: str, bibliographic=False) -> str:
        code = cls._name_to_code.get(name.lower(), "")
        if bibliographic:
            # Convert to bibliographic code if requested
            return cls._T_to_B_map.get(code, code)
        return code

    @classmethod
    def t_to_b(cls, code: str) -> str:
        return cls._T_to_B_map.get(code.lower(), code.lower())

    @classmethod
    def b_to_t(cls, code: str) -> str:
        return cls._B_to_T_map.get(code.lower(), code.lower())


if __name__ == "__main__":
    print(PyLangISO639_2.code_to_name("eng"))       # English
    print(PyLangISO639_2.code_to_name("chi"))       # Chinese
    print(PyLangISO639_2.code_to_name("ger"))       # German, bibliographic input
    print(PyLangISO639_2.name_to_code("Chinese"))   # chi
    print(PyLangISO639_2.name_to_code("German"))    # deu
    print(PyLangISO639_2.name_to_code("German", bibliographic=True))  # ger
    print(PyLangISO639_2.t_to_b("deu"))             # ger
    print(PyLangISO639_2.b_to_t("ger"))             # deu
